### ISSUE TITLE
Meaning of the "L" in "L_HR" inside the PineTime terminal watch face?

### ISSUE THREAD

**Issue by arduino-man** [ZephyrLabs/Watchfaces#11]
Hi there,

Since you are the original creator of the PineTime terminal watch face, I was wondering.. what does the "L" in "L_HR" mean in the Terminal watch face you created?

Thanks a lot

**Comment by theking8694** [comment]
Y'know, it's been a long time, and I don't remember why it is like that. I think it's just to match the reference image I used? There may have been another reason. Sorry that I can't give a good answer.

**Comment by arduino-man** [comment]
Thanks for answering :)  May I ask which reference image?

**Comment by theking8694** [comment]
![P1AMwObXCgsRVq8iu73T-ZuLkZ6gcK2R9i441-ciPp4.jpg](https://user-images.githubusercontent.com/27705324/177205197-b3e8376a-cf99-4faa-9095-9ec3696f2b9a.jpg)
It was this image, from Reddit. I don't know who the original poster or creator is though, since it is not the original source.

**Comment by arduino-man** [comment]
Interesting, thank you :)
