### ISSUE TITLE
Notifaction Vibration motorcontroller in Infinitime

### ISSUE THREAD

**Issue by petterhs** [ZephyrLabs/Watchfaces#3]
Hi,

Found your implementation of motorcontroller for vibrations in in the Terminal watchface. Thanks!! I'm wondering if there is a reason this is not merged into Infinitime yet and if you are planning to send a PR on it.

**Comment by ZephyrLabs** [comment]
Hello, 
sorry for the late reply,
I actually didn't make the vibrations for notification feature in the terminal watchface, 
@jlukanc1 worked on that, and wrote the code for it, 
I believe he can tell you more about that here :)
